version: '3'
services:
  rest-number:
    image: "stefanini/rest-number:1.0.0-SNAPSHOT"
    ports:
      - "8701:8701"
  rest-book:
    image: "stefanini/rest-book:1.0.0-SNAPSHOT"
    ports:
      - "8702:8702"

    #Overrides the configuration placed on application.properties from rest-book
    environment:
      - NUMBER_PROXY_MP_REST_URI=http://rest-number:8701